# This is a basic workflow to help you get started with Actions

name: Replace variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        environment: ['dev', 'ci', 'staging', 'prod']
    runs-on: ubuntu-latest
    environment: '${{ matrix.environment }}'
    steps:
      - name: Checkout code
        run: |
          echo "::set-output name=${{ matrix.environment }}::${{secrets.KEY}}"

  final:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Test
         run: |
           echo "${{needs.build.outputs.dev-key}} ${{needs.build.outputs.ci-key}} ${{needs.build.outputs.staging-key}} ${{needs.build.outputs.prod-key}}"
