# This is a basic workflow to help you get started with Actions

name: Replace variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        environment: ['dev', 'ci', 'staging', 'prod']
    runs-on: self-hosted
    outputs:
      key: '${{ secrets.KEY }}'
    steps:
      - name: Checkout code
        run: |
          echo "::set-env name=ENVIRONMENT::matrix.environment"
           echo ${{secrets.KEY}} | sed 's/./& /g'

  # final:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    steps:
  #      - env:
  #          OUTPUT1: ${{needs.build.outputs.key}}
  #        run: echo "$OUTPUT1"
