# This is a basic workflow to help you get started with Actions

name: Replace variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        environment: ['dev', 'ci', 'staging', 'prod']
    runs-on: ubuntu-latest
    environment: '${{ matrix.environment }}'
    steps:
      - name: Checkout code
        run: |
          # echo "${{ matrix.environment }}-key=${{secrets.KEY}}" >> $GITHUB_OUTPUT
          # echo $GITHUB_OUTPUT
          echo "::set-output name=${{ matrix.environment }}::${{secrets.KEY}}"

  final:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - env:
           OUTPUT1: ${{needs.build.outputs.dev-key}}
           OUTPUT2: ${{needs.build.outputs.ci-key}}
           OUTPUT3: ${{needs.build.outputs.staging-key}}
           OUTPUT4: ${{needs.build.outputs.prod-key}}
         run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3 $OUTPUT4"
