# This is a basic workflow to help you get started with Actions

name: Replace variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Substitute common variables in appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appConfig.json'
        env:
          url: "https://www.google.com"
          forgerock.loginurl: "https://www.google.com"
          
      - name: Set the value in bash
        run: echo cat appConfig.json
